<a href="https://colab.research.google.com/github/jai8004/Data-Science/blob/main/DeepLearning/FrameworkIntro/Tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Install TensorFlow**

In [11]:
! pip install "tensorflow>=1.15,<2.0" 
! pip install --upgrade tensorflow-hub

In [12]:
#check tf version 
import tensorflow as tf
tf.__version__

'1.15.5'

# Tesnor

In tensorflow every values is stored as 

1.   Tensor rather than beign stored as int, strings, float etc.
2.   Tesnor size can vary





In [13]:
#0-dimension tensor
A = tf.constant(1234)

#1-dimension tensor
B = tf.constant([1234,2323,4332])

#2-dimension tensor
C = tf.constant([[1234,2323,4332],[231,2331,4568]])

print(A)
print(B)
print(C)



Tensor("Const_28:0", shape=(), dtype=int32)
Tensor("Const_29:0", shape=(3,), dtype=int32)
Tensor("Const_30:0", shape=(2, 3), dtype=int32)


# Session 



1. In TF1.x we have the concept of session.It's handeld automatically in TF2.

2. A session allows to execute graphs or part of graphs. It allocates resources (on one or more machines) for that and holds the actual values of intermediate results and variables.

3. tf.Session() create session instance(sess) which intiate using sess.run() command and evaluate the tensor(A,B,C) intiated inside session and return the result.

In [14]:
hello_cons = tf.constant('Hello World')
with tf.Session() as sess:
  #0-dimension tensor
  out_A = sess.run(tf.constant(1234))
  out_B = sess.run(tf.constant([1234,2323,4332]))
  out_C = sess.run(tf.constant([[1234,2323,4332],[231,2331,4568]]))
 
  print(out_A)
  print(out_B)
  print(out_C)



1234
[1234 2323 4332]
[[1234 2323 4332]
 [ 231 2331 4568]]
