<a href="https://colab.research.google.com/github/jai8004/Data-Science/blob/main/DeepLearning/Basics/PyTorch_Basics_Tensors_%26_Gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html


In [ ]:
import torch

#### Tensors

In [ ]:
# Number
t1 = torch.tensor(4.)
#Vector
t2 = torch.tensor([1., 2, 3, 4])
#Matrix
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
#3-Dimensional Array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])

In [ ]:
# Matrix
t5 = torch.tensor([[5., 6, 11],
                   [7, 8],
                   [9, 10]])
t5

ValueError: ignored

In [ ]:
print(f'Shape : {t1.shape}, Data Type : {t1.dtype}')
print(f'Shape : {t2.shape}, Data Type : {t2.dtype}')
print(f'Shape : {t3.shape}, Data Type : {t3.dtype}')
print(f'Shape : {t4.shape}, Data Type : {t4.dtype}')


Shape : torch.Size([]), Data Type : torch.float32
Shape : torch.Size([4]), Data Type : torch.float32
Shape : torch.Size([3, 2]), Data Type : torch.float32
Shape : torch.Size([2, 2, 3]), Data Type : torch.float32


#### Observations :

1. t1 is just a number that's why it's having dimension as zero.
2. t2 is tensor with float and int in pytorch if you provide different data types then all values are converted to float.
3. t3 and t4 are n dimensional matrix
4. t5 ValueError is thrown because the lenghts of the rows didnt match

### Tensor opeartions and Gradients


In [ ]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# Compute derivatives
y.backward()

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


#### Observations:
1. dy/dw has the same value as x, i.e., 3, and dy/db has the value 1.
2. x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

### Tensor functions

In [ ]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])